# Generated by Django 3.1.2 on 2021-02-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
