# Generated by Django 3.1.6 on 2021-02-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0006_auto_20210218_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('xs', 'extra small'), ('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('o', 'one size')], max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='my_shop.product')),
            ],
        ),
    ]
