# Generated by Django 3.1.6 on 2021-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0007_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(related_name='product', to='my_shop.Product'),
        ),
    ]
