# Generated by Django 3.1.6 on 2021-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0009_auto_20210219_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
