# Generated by Django 3.1.6 on 2021-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0010_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
