# Generated by Django 3.1.6 on 2021-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0012_auto_20210221_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
