# Generated by Django 3.1.6 on 2021-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0014_auto_20210228_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
