# Generated by Django 3.1.6 on 2021-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0015_product_composition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/category/'),
        ),
    ]
