# Generated by Django 3.1.7 on 2021-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0017_auto_20210310_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
