# Generated by Django 3.1.6 on 2021-03-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slide_of_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/lookbook')),
                ('image2', models.ImageField(blank=True, upload_to='images/lookbook')),
                ('description', models.TextField(max_length=300)),
                ('description2', models.TextField(max_length=300)),
                ('collection', models.ManyToManyField(to='lookbook.Collection')),
            ],
        ),
    ]
