# Generated by Django 3.1.7 on 2021-03-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide_of_collection',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='slide_of_collection',
            name='image2',
        ),
    ]
