# Generated by Django 3.1.7 on 2021-03-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0017_auto_20210310_0227'),
        ('orders', '0002_auto_20210308_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='my_shop.size'),
        ),
    ]
